import { Metadata } from "next";

export const metadata: Metadata = {
    title: "D.MS 내 정보",
    description: "Generated by create next app",
};

export default function RootLayout ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>
    )

}