import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
    title: "D.MS 로그인",
    description: "Generated by create next app",
};

export default function RootLayout ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            {children}
        </>
    )
}