import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "D.MS 영화 목록",
    description: "Generated by create next app",
};

export default function RootLayout ({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
        </>
    )
}