import { Metadata } from "next";

export const metadata: Metadata = {
    title: "M.DS 아이디/비밀번호 찾기",
    description: "Generated by create next app",
};

export default function RootLayout ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            {children}
        </>
    )
}