import { Metadata } from "next";


export const metadata: Metadata = {
    title: "D.MS 회원가입",
    description: "Generated by create next app",
};

export default function RootLayout ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            {children}
        </>
    )
}